version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: generic-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - generic-db:/var/lib/postgresql/data
      - ../migrations/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # Use pg_isready to check postgres is running. Substitute different
      # user `postgres` if you've setup differently to config/pgpass-mainnet
      test: ['CMD-SHELL', 'pg_isready -U postgres -p 5432']
      interval: 20s
      timeout: 5s
      retries: 5

volumes:
  generic-db:
